### ISSUE TITLE
Showcase at webmonetization workshop

### ISSUE THREAD

**Issue by michielbdejong** [solid/webmonetization#15]
Tomorrow I'll record and upload a lightning talk for https://dev.to/coil/announcing-the-web-monetization-workshop-wmw-2oid
I'll briefly mention all Solid-related webmonetization projects but mainly just point at what we're working on, because my total presentation there will only be 5 minutes.

**Comment by michielbdejong** [comment]
It will be "a quick summary of how we're dealing with webmonetization, payment pointers and paywalls in https://solidproject.org".

**Comment by michielbdejong** [comment]
Let me know if there is anything in particular that you want me to point to as part of this.

**Comment by michielbdejong** [comment]
https://vimeo.com/577181119

**Comment by michielbdejong** [comment]
I guess my presentation will be added to one of the two showcase sessions; not sure what the timezones on https://workshop.webmonetization.org/schedule are. I see it as (this is probably displaying to me as Amsterdam time):
* 28 July 17:00-17:30 Showcase 1
* 29 July 00:00-00:30 Showcase 2
* 29 July 17:00-17:30 Architecture 1
* 30 July 00:00-01:00 Architecture 2

**Comment by rubensworks** [comment]
Nice overview @michielbdejong! :)
